<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Flag</name>
   <tag></tag>
   <elementGuidId>6bfa6e53-f95d-499c-8f51-b685569e5081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[normalize-space(text())='Flag']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
