<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Log in and Log out</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a53993b6-c627-4841-b8c9-0edb503c8be0</testSuiteGuid>
   <testCaseLink>
      <guid>e7ceceab-b65b-44fa-a1d8-3bfab2949f8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>aabe5104-90f3-4155-8a85-665935b4baa8</id>
         <masked>false</masked>
         <name>Username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Login Office</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>031429c5-dc1a-43d6-987a-078aaebeb61d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Excel Test/Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583b5ef7-4f7b-4c86-aa71-2066f423c73f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fea2383b-132d-485b-9671-cf25595803a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67e249ca-92dd-46a6-8143-d3d574028054</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2b8eaae-56da-4a35-8e92-5ad7a462eb07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Log Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
