<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LINK_TO_CHANGE</name>
   <tag></tag>
   <elementGuidId>333ced22-336f-4404-940c-6a3188ae6780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article-content']/div/div[2]/div/div/div/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.mb-3.text-justify > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd797f3e-7d2f-4934-8e52-37d5d4f3b2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gla-az-aurora-web-site-test-sr344.azurewebsites.net/eSMS%20Categories/article/edit/1217/2091</value>
      <webElementGuid>f053a8d3-afc9-4833-a02f-993f74629adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>3deadf47-154d-4d8c-a777-e6609c8fd380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LINK_TO_CHANGE</value>
      <webElementGuid>053a48da-7390-458a-b33c-55c3e6864b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article-content&quot;)/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;flex-grow-1&quot;]/div[@class=&quot;mud-paper mud-elevation-2 mx-auto my-4 pa-6&quot;]/div[@class=&quot;pb-4&quot;]/div[@class=&quot;content-view&quot;]/div[1]/p[@class=&quot;mb-3 text-justify&quot;]/a[1]</value>
      <webElementGuid>5dc5070e-f793-4074-b4a7-86cf3fc0525a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article-content']/div/div[2]/div/div/div/div/p/a</value>
      <webElementGuid>ff09d4c5-b193-4f97-845a-f8ac7fcf61fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LINK_TO_CHANGE')]</value>
      <webElementGuid>7f079e12-593f-4115-aa29-0c7abc651907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test doc test doc (2.00)'])[1]/following::a[1]</value>
      <webElementGuid>8aaa3591-d337-4870-b3c3-5a4d4a05d3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wildcard:'])[1]/following::a[1]</value>
      <webElementGuid>a63c6edc-2698-42ba-9363-f2f8745a3d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/preceding::a[1]</value>
      <webElementGuid>6978c51a-c61a-4581-b030-808c719af5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://gla-az-aurora-web-site-test-sr344.azurewebsites.net/eSMS%20Categories/article/edit/1217/2091')]</value>
      <webElementGuid>45b6e769-e848-469d-b6f3-fb174ab033c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>f5ee3b7d-0664-4725-ba8e-1f014447e098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gla-az-aurora-web-site-test-sr344.azurewebsites.net/eSMS%20Categories/article/edit/1217/2091' and (text() = 'LINK_TO_CHANGE' or . = 'LINK_TO_CHANGE')]</value>
      <webElementGuid>417ec940-3e5a-4eb5-82e1-c3f34b7f137d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
