<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_123 - Test</name>
   <tag></tag>
   <elementGuidId>d019563b-de57-4f0e-9f94-6bdd2d6e07f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article-sidebar']/div/aside/div/div[2]/div/div/ul/li[2]/div/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>7109899f-8096-4b0f-8d4e-2f80bc72baf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123 - Test</value>
      <webElementGuid>c584f30e-311b-4ecb-b50f-edcb6eacd744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article-sidebar&quot;)/div[@class=&quot;mud-height-full&quot;]/aside[@class=&quot;mud-drawer mud-drawer-pos-left mud-drawer--open mud-drawer--initial mud-drawer-lg mud-drawer-clipped-never mud-elevation-1 mud-drawer-persistent theme-background&quot;]/div[@class=&quot;mud-drawer-content&quot;]/div[@class=&quot;d-none d-xl-flex d-xxl-none&quot;]/div[@class=&quot;flex-grow-1&quot;]/div[@class=&quot;ml-2&quot;]/ul[@class=&quot;mud-treeview mud-treeview-dense mud-treeview-hover mud-treeview-selected-primary mud-treeview-checked-default mt-4&quot;]/li[@class=&quot;mud-treeview-item&quot;]/div[@class=&quot;mud-treeview-item-content&quot;]/div[@class=&quot;d-flex align-center f-width tree-node c-pointer&quot;]/b[1]</value>
      <webElementGuid>a16372f6-50d6-496c-8dba-634615da52bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article-sidebar']/div/aside/div/div[2]/div/div/ul/li[2]/div/div/b</value>
      <webElementGuid>6ffc830d-05c6-4d5a-993f-1def9872cdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[1]/following::b[1]</value>
      <webElementGuid>228ab0bf-3675-4fd5-a983-4fb31e89bada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wildcard:'])[1]/following::b[1]</value>
      <webElementGuid>168db82c-a3c6-4a99-9884-571d701c38a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>4f02db76-5f83-4ccb-8897-e381e172b953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '123 - Test' or . = '123 - Test')]</value>
      <webElementGuid>72788bff-cb6c-4b11-9123-60e3fd4a946d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
