<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add your comment_mud-overlay-scrim mud-_c52764</name>
   <tag></tag>
   <elementGuidId>27590a92-f160-4130-8a33-03115eba6efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article-content']/div/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ae-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dc7e5f8-940d-4363-9be8-7b0b7ea1506f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ae-body</value>
      <webElementGuid>2843c79e-0ffd-4f9f-894f-ef92d208157c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article-content&quot;)/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;flex-grow-1&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mx-auto&quot;]/div[@class=&quot;mud-paper mud-elevation-2 my-4 pa-4&quot;]/div[@class=&quot;ae-container&quot;]/div[@class=&quot;ae-body&quot;]</value>
      <webElementGuid>13a78caf-9bf9-45a4-89c6-9ac6326fbd96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article-content']/div/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>049599c2-3e3c-47fd-b3d1-f5f6339219ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='link_off'])[1]/following::div[1]</value>
      <webElementGuid>2af06082-7436-4810-bc09-16ed01826ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='link'])[1]/following::div[1]</value>
      <webElementGuid>552d704c-917b-4f01-aa54-3f7f6ccf8ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[2]/preceding::div[2]</value>
      <webElementGuid>4eeb6b73-1a41-4303-b4a3-0065d674ad22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version History'])[1]/preceding::div[12]</value>
      <webElementGuid>c3241d70-258d-4112-8809-e005bfb7f870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>5aad4b55-572f-4050-99a9-6ab6154f8182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog_1e72e6c1']/div/div</value>
      <webElementGuid>9232fd16-b2eb-4c82-8ddc-130b9008928c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>26c13476-dcd0-405c-9b08-78f387c569f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
