<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_link</name>
   <tag></tag>
   <elementGuidId>e7a3ca61-226b-46d7-9c82-23cc6e7046e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article-content']/div/div/div/div/div/div/div/div[2]/div[7]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bd2895a2-d4d0-4593-aab5-849927d7ee55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>981fd93f-8fb3-413b-8896-091f510f8d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>f674818f-36a9-4e18-8d20-06365c693077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article-content&quot;)/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;flex-grow-1&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mx-auto&quot;]/div[@class=&quot;mud-paper mud-elevation-2 my-4 pa-4&quot;]/div[@class=&quot;ae-container&quot;]/div[@class=&quot;ae-header&quot;]/div[@class=&quot;ae-toolbar&quot;]/div[@class=&quot;ae-btn-group&quot;]/button[@class=&quot;ae-toolbar-btn&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>c7d134e8-edc5-491a-b592-9764288f7ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article-content']/div/div/div/div/div/div/div/div[2]/div[7]/button[2]/i</value>
      <webElementGuid>39eb6cbc-285e-49fd-9656-642ccd58cb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bookmark_add'])[1]/following::i[1]</value>
      <webElementGuid>490ab83d-9974-486d-b957-a6b68f1b9033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::i[2]</value>
      <webElementGuid>eba379ed-7ce4-42fa-9888-0b9846e01458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='link_off'])[1]/preceding::i[1]</value>
      <webElementGuid>f24145e1-a109-49d8-be3c-f712e4a583a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINK_TO_CHANGE'])[1]/preceding::i[2]</value>
      <webElementGuid>dd5e0548-b5fe-4efd-94dc-f4bf62809efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button[2]/i</value>
      <webElementGuid>d592204b-247e-406e-965a-dc04e32e1b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'link' or . = 'link')]</value>
      <webElementGuid>e21d9e73-a71f-4413-a539-182d952d2754</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
