<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Positions_mud-input-slot mud-input-ro_a16c33</name>
   <tag></tag>
   <elementGuidId>efb2e72e-4585-4db8-939b-bcd05a641e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mud-input-slot.mud-input-root.mud-input-root-filled.mud-input-root-adorned-end.mud-input-root-margin-dense</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d6dd415-a8e8-4572-9713-9729b98960a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-input-slot mud-input-root mud-input-root-filled mud-input-root-adorned-end mud-input-root-margin-dense</value>
      <webElementGuid>c4605e15-b3e0-4b18-adb2-c6771a6035e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b1b2812-8699-4514-939b-124fdba2c4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>801164b9-6b99-4e2e-8268-f42543bb2d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>524288</value>
      <webElementGuid>cb4d0fed-dfd9-47c8-9000-3dcfc904580d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_e0cd9b9732c04087b47fcf7e099a96c4&quot;)/div[2]/div[@class=&quot;mud-dialog-content pa-0&quot;]/div[@class=&quot;d-flex flex-column f-width parent-height theme-background&quot;]/div[@class=&quot;flex-grow-1 d-flex flex-column parent-height no-scroll&quot;]/div[@class=&quot;flex-grow-0 px-6 py-3&quot;]/div[@class=&quot;mud-input-control mud-input-control-margin-dense mud-input-input-control&quot;]/div[@class=&quot;mud-input-control-input-container&quot;]/div[@class=&quot;mud-input mud-input-filled mud-input-adorned-end mud-input-margin-dense mud-input-underline&quot;]/input[@class=&quot;mud-input-slot mud-input-root mud-input-root-filled mud-input-root-adorned-end mud-input-root-margin-dense&quot;]</value>
      <webElementGuid>a0629fc6-e1ba-4537-af05-45e1a4d37625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>68776bc7-3220-4bd2-ba92-d0c2611e596f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_e0cd9b9732c04087b47fcf7e099a96c4']/div[2]/div[4]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d62036ae-e1fb-4baa-93df-9b8dbc973206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e0f59f23-cb3c-44fa-99e5-d37de3cd6155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>f00d8c58-63a1-43bf-9362-9a6cd9080a66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
