<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wildcard_mud-checkbox-input</name>
   <tag></tag>
   <elementGuidId>e3f4f121-0cce-4b79-b1dd-cdae11a067fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mud-checkbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a9a9060-c938-4faa-ae55-2482e0d56b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>de4561db-3869-439f-9a1c-0f8a8c014fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2a5d26f4-7cb1-472b-a447-dc6842783e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-checkbox-input</value>
      <webElementGuid>c7dce7cb-b226-4266-bc54-b5f32be6d3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox31a9c31f&quot;)/span[@class=&quot;mud-button-root mud-icon-button mud-icon-button-color-default mud-ripple mud-ripple-checkbox&quot;]/input[@class=&quot;mud-checkbox-input&quot;]</value>
      <webElementGuid>b482636e-ff13-476e-90cf-2fa081cca08a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>788f7900-1b0c-4daa-8888-3409885b9bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkbox31a9c31f']/span/input</value>
      <webElementGuid>3d017699-bd81-41dc-b27b-18608026380f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wildcard:'])[1]/following::input[1]</value>
      <webElementGuid>5cd5debd-9e7d-416a-9118-c14d25cd6968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will return search result matching atleast one term from the query in any sequence'])[1]/following::input[1]</value>
      <webElementGuid>c6baf0f4-fad7-496b-a7c8-9b576d515a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/preceding::input[1]</value>
      <webElementGuid>90d0a4f1-1367-4e5b-8a49-a4525df28a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[2]/preceding::input[1]</value>
      <webElementGuid>483b9d6b-3c2f-47ac-af90-4c12b85c638b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/input</value>
      <webElementGuid>f3e638e1-6379-44c8-aff1-0185a8b4f338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>476b75d7-a85f-4d7d-8faa-04d450bd1b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkboxf25848e7']/span/input</value>
      <webElementGuid>cdfdcbf9-3274-4117-ad43-c4a145d0271c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkbox8071dece']/span/input</value>
      <webElementGuid>297026c4-16ca-418e-8e3e-9a3da50916b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkboxc9eef1be']/span/input</value>
      <webElementGuid>655f5e75-d4df-4114-815f-c1393f877721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkboxe61800a6']/span/input</value>
      <webElementGuid>a4c60bf2-46ff-49ec-b581-dd460043d9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkbox7425f36b']/span/input</value>
      <webElementGuid>93466ea0-4bee-4a7e-ade7-687c8e3acfc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
