<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New document_mud-input-slot mud-input_3a7dbf</name>
   <tag></tag>
   <elementGuidId>671ed3bf-b568-4755-8c6c-c3b2219cd45f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mud-input-slot.mud-input-root.mud-input-root-outlined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c99450f-d5ed-4ab0-a8fc-98375acc26d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-input-slot mud-input-root mud-input-root-outlined</value>
      <webElementGuid>729f5500-4cd4-425b-b82f-107aad55d319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>833219f9-8b59-47a4-b9ae-7dcc839ecf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter name of the document</value>
      <webElementGuid>bfa4a550-b1cb-4dc3-9f2a-5565c01a9f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1863857d-4026-4609-8253-a8a3a1495f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>524288</value>
      <webElementGuid>e41740ca-ef1e-4bc2-91fe-5e208ee21367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_3038bbc9975b43458e4e4e9dc7908bc9&quot;)/div[2]/div[@class=&quot;mud-dialog-content&quot;]/form[1]/div[@class=&quot;mud-input-control mud-input-input-control&quot;]/div[@class=&quot;mud-input-control-input-container&quot;]/div[@class=&quot;mud-input mud-input-outlined mud-shrink&quot;]/input[@class=&quot;mud-input-slot mud-input-root mud-input-root-outlined&quot;]</value>
      <webElementGuid>c9c7ccb3-0aca-4de6-9f43-e1d8299384a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>d32848ff-b607-4617-8fdd-997511454d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_3038bbc9975b43458e4e4e9dc7908bc9']/div[2]/div[4]/form/div/div/div/input</value>
      <webElementGuid>4562fb49-4511-4b10-8553-44465aa8fe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c7ce8b0b-5d4a-4a78-b86f-abd37480b4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter name of the document']</value>
      <webElementGuid>20fc405f-e445-402c-ac1f-752fee6bf064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
