<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Aurora Web_mud-input-slot mud-input-r_127a58_1</name>
   <tag></tag>
   <elementGuidId>58713fb3-228b-4955-b3cf-829db7be96b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b952b0f0-d491-48e7-ab8f-cf591c72c60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-input-slot mud-input-root mud-input-root-outlined</value>
      <webElementGuid>66b35407-cdbf-4a04-832b-9ea9b1e57b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7fb7cb4e-d790-465f-aa07-bd0218d202ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>d1f986cd-428c-485a-ab5f-0da3d70e9da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7187c0f9-9826-48d8-8e06-4fa4ca0509a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>524288</value>
      <webElementGuid>ceb981b7-9faf-441c-a883-e1f5fec6acbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;mud-layout&quot;]/div[@class=&quot;login d-flex align-center northern-marine&quot;]/div[@class=&quot;login-container mx-auto f-height d-flex flex-column&quot;]/div[@class=&quot;flex-grow-1 mt-16 text-center&quot;]/form[@class=&quot;mud-form&quot;]/div[@class=&quot;mud-input-control mud-input-required mud-input-input-control mb-3 f-width&quot;]/div[@class=&quot;mud-input-control-input-container&quot;]/div[@class=&quot;mud-input mud-input-outlined mud-shrink&quot;]/input[@class=&quot;mud-input-slot mud-input-root mud-input-root-outlined&quot;]</value>
      <webElementGuid>03aaeb37-ff2b-4790-b569-128cef317cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>8ee180c0-2531-465d-8edd-1d0e3b06019d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div/form/div[2]/div/div/input</value>
      <webElementGuid>844a87e9-2be4-4306-ade9-7b665acb5336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aurora Web'])[1]/following::input[2]</value>
      <webElementGuid>07a6c9a9-7750-460e-9880-28cf3ffa23d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::input[1]</value>
      <webElementGuid>52aa95ff-0d11-4168-b799-4a65584c72a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::input[1]</value>
      <webElementGuid>8f38c2c5-5f05-46cb-ba48-7b612bc016ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>b4114435-cde9-41c0-9333-4a0c8c86a156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>92fe35e4-8179-4d3a-8b23-34e50de08b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
