<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_this document is edited</name>
   <tag></tag>
   <elementGuidId>4ce396d5-9aa0-4b5a-9fcb-10a32b9cd118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article-content']/div/div[2]/div/div/div/div/p/ins</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
      <webElementGuid>406fd0db-442f-4460-ac7f-1fc6650653dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> this document is edited</value>
      <webElementGuid>8e36171c-b4f1-42f9-927b-77862adcfddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article-content&quot;)/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;flex-grow-1&quot;]/div[@class=&quot;mud-paper mud-elevation-2 mx-auto my-4 pa-6&quot;]/div[@class=&quot;pb-4&quot;]/div[@class=&quot;content-view&quot;]/div[1]/p[@class=&quot;mb-3 text-justify&quot;]/ins[1]</value>
      <webElementGuid>f25d83b4-ce60-48c1-9a5a-1beb2951dbd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article-content']/div/div[2]/div/div/div/div/p/ins</value>
      <webElementGuid>678e01e6-8f2b-41d6-8b00-01f43a38c7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINK_TO_CHANGE'])[1]/following::ins[1]</value>
      <webElementGuid>693ad05a-2de1-4f3c-be1b-43eba7d4a511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test doc test doc (4.00)'])[1]/following::ins[1]</value>
      <webElementGuid>530f9da6-775a-4ec3-80fd-aa050c26e791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/preceding::ins[1]</value>
      <webElementGuid>704175d5-2d8b-43da-91a9-331d443aaebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins</value>
      <webElementGuid>c8e34042-f13f-452e-879d-c0308ea48d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ins[(text() = ' this document is edited' or . = ' this document is edited')]</value>
      <webElementGuid>850e21a3-c325-4284-acc8-a19c1aa52362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
