<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Routine</name>
   <tag></tag>
   <elementGuidId>e262c37e-5b22-4842-af2e-2a6b92748277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_e924e94b']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1ddc0fff-fe4b-4075-80aa-55fd7e73e445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-typography mud-typography-body1 mud-inherit-text</value>
      <webElementGuid>fb68dc3a-b2ed-4dc6-ab96-6bd6460fc8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Routine</value>
      <webElementGuid>3770663d-e58e-4336-af25-b6139b8b45ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_e924e94b&quot;)/div[@class=&quot;mud-list-item-text&quot;]/p[@class=&quot;mud-typography mud-typography-body1 mud-inherit-text&quot;]</value>
      <webElementGuid>729168cb-acc8-4fb1-b032-8d46dc721a02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_e924e94b']/div/p</value>
      <webElementGuid>478527d3-427b-4878-affc-1336a1b88f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Select Classification -'])[1]/following::p[3]</value>
      <webElementGuid>84232923-19c2-4811-8f37-084593607449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::p[4]</value>
      <webElementGuid>bb1ce917-17b6-4134-997e-af03608ce15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AURORA'])[1]/preceding::p[1]</value>
      <webElementGuid>24ec4572-f595-430f-87ab-59c964decc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sean Testing'])[1]/preceding::p[1]</value>
      <webElementGuid>54ee287c-9f9a-412c-b250-78015ef79601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/p</value>
      <webElementGuid>80b812e3-d702-4bb4-8478-6a9b087ad395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Routine' or . = 'Routine')]</value>
      <webElementGuid>ac1ec6c3-7457-4664-b1a6-9f4601f42dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_3f1815d4']/div/p</value>
      <webElementGuid>df1ac692-d701-443c-b8e9-d98b0bdb2c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
