<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Test doc</name>
   <tag></tag>
   <elementGuidId>af2cbad4-1809-4442-b425-e7550dc0bd7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div[2]/div[3]/div/div/table/tbody/tr[4]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>752896cb-afc3-4a19-91b0-ca9a7277e95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test doc</value>
      <webElementGuid>3985c4b7-3f9d-481a-ad6d-2e6fc733fb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;mud-layout mud-drawer-open-responsive-md-left mud-drawer-left-clipped-always&quot;]/div[@class=&quot;mud-main-content&quot;]/div[@class=&quot;mud-container mud-container-maxwidth-false d-flex flex-column px-8&quot;]/div[@class=&quot;flex-grow-1&quot;]/div[@class=&quot;mud-table mud-simple-table mud-table-dense mud-table-hover mud-table-bordered mud-table-sticky-header mud-elevation-1 aurora-table&quot;]/div[@class=&quot;mud-table-container&quot;]/table[1]/tbody[1]/tr[4]/td[1]</value>
      <webElementGuid>02f42efc-9171-42b9-bb30-d30357c882a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div[2]/div[3]/div/div/table/tbody/tr[4]/td</value>
      <webElementGuid>5eea9846-f442-4e33-bc4b-eab8488deb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[3]/following::td[3]</value>
      <webElementGuid>aa1244df-a69c-472c-b746-6e56043de78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='unpublished test'])[1]/following::td[5]</value>
      <webElementGuid>b5b2d14d-b9eb-4d7f-9f0a-79c96632a707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test doc'])[2]/preceding::td[1]</value>
      <webElementGuid>2132de6f-ef8c-4c0f-a2d6-8ce1ea098896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[4]/preceding::td[3]</value>
      <webElementGuid>bde8fa78-56dc-44b0-b33f-c2191041f48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td</value>
      <webElementGuid>ad22e770-4392-4101-82dd-5c12b001ccfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'test doc' or . = 'test doc')]</value>
      <webElementGuid>963f2f70-56c9-405d-a4b9-05ee264ae0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div[2]/div[3]/div/div/table/tbody/tr[4]/td[2]</value>
      <webElementGuid>60b27e39-214c-4347-9d13-97cf1f3af799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test doc'])[1]/following::td[1]</value>
      <webElementGuid>3d5c4525-2266-4fa3-99ab-810830084798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[3]/following::td[4]</value>
      <webElementGuid>a8d65478-1ed5-4aec-9d45-a42f229ca5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[4]/preceding::td[2]</value>
      <webElementGuid>4fa157d7-ad28-4fd6-9c53-c33f7d297c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page:'])[1]/preceding::td[5]</value>
      <webElementGuid>c97f4b05-0aeb-4703-8eb6-5ae430e4c13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>97a84622-f943-4813-b154-ce8446e6cefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div[2]/div[3]/div/div/table/tbody/tr[7]/td</value>
      <webElementGuid>68f60832-9086-46de-bc1b-b78a8dd50efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[5]/following::td[3]</value>
      <webElementGuid>8ed79a03-847f-4ccc-9266-3c5a6bbcee5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[2]/following::td[5]</value>
      <webElementGuid>c0ac0379-4cce-4a62-8273-798c6f18dfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No File Uploaded'])[4]/preceding::td[1]</value>
      <webElementGuid>5cddba34-b712-4a3d-bc65-02e59419872b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No File Uploaded'])[5]/preceding::td[2]</value>
      <webElementGuid>2eb66be8-1089-4b14-aea9-0a6b56eb25f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test doc']/parent::*</value>
      <webElementGuid>de1c1e71-6f86-44ca-b72d-5460caad5982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td</value>
      <webElementGuid>2d13dcb5-fc98-4546-a1cb-6bc51199740e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Test doc' or . = 'Test doc')]</value>
      <webElementGuid>564041de-e256-41b1-8268-42253ecb67c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
