<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_31</name>
   <tag></tag>
   <elementGuidId>c60a306d-fd4b-48d4-8d0a-145dba69c1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[37]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44542f16-899a-48b1-96c2-2627a2dc385b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a7c9175-3d0f-406f-ad6a-8f5cb20dc058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-button-root mud-icon-button mud-ripple mud-ripple-icon mud-picker-calendar-day mud-day mud-range mud-range-selection mud-range-selection-primary</value>
      <webElementGuid>7ad19fb5-ffae-4c31-81f5-8a0f99b84426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Wednesday, 31 January 2024</value>
      <webElementGuid>8f67df95-76f4-402d-ae95-ae5529e3717d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.closest('.mud-picker-calendar-content').style.setProperty('--selected-day', 32);</value>
      <webElementGuid>532a7d60-613b-441f-a6b8-02f957055d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>dd2270a5-d410-45cf-a223-04d6331c085f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popovercontent-3097d9a9-ba79-4393-bc8c-56c778b2b2e5&quot;)/div[@class=&quot;mud-picker-inline-paper&quot;]/div[@class=&quot;mud-paper mud-elevation-8 mud-picker mud-picker-paper mud-picker-view mud-picker-open mud-picker-popover-paper&quot;]/div[@class=&quot;mud-picker-container&quot;]/div[@class=&quot;mud-picker-content&quot;]/div[@class=&quot;mud-picker-calendar-content mud-picker-calendar-content-2&quot;]/div[@class=&quot;mud-picker-calendar-container&quot;]/div[@class=&quot;mud-picker-calendar-transition mud-picker-slide-transition&quot;]/div[@class=&quot;mud-picker-calendar&quot;]/button[@class=&quot;mud-button-root mud-icon-button mud-ripple mud-ripple-icon mud-picker-calendar-day mud-day mud-range mud-range-selection mud-range-selection-primary&quot;]</value>
      <webElementGuid>47b41962-0af0-4864-883c-5c2254a0791e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[37]</value>
      <webElementGuid>4ebf3c65-10ac-4006-a83f-28e97d9c38ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popovercontent-3097d9a9-ba79-4393-bc8c-56c778b2b2e5']/div/div/div/div[2]/div/div/div[2]/div/button[32]</value>
      <webElementGuid>3b81ac94-24af-4761-9f48-05133889086c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[32]</value>
      <webElementGuid>3fef607c-d488-4772-b2c2-eaa0a204bd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[32]</value>
      <webElementGuid>a39e3103-5834-401d-abdf-af2fed33a3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[2]/preceding::button[14]</value>
      <webElementGuid>85497822-32c9-4e58-8d33-703fbcd2d169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[2]/preceding::button[14]</value>
      <webElementGuid>e4f0f063-cf58-4e16-8a07-b647d15b4be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[32]</value>
      <webElementGuid>7f092655-5846-464b-8d19-ff5a9e3339cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '31' or . = '31')]</value>
      <webElementGuid>09c54f40-6087-42a6-85b8-f714d1609ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
