<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Published Date_mud-input-slot mud-inp_a55268</name>
   <tag></tag>
   <elementGuidId>4a553e27-4c25-4b8e-acde-38104c53126d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mud-input-slot.mud-input-root.mud-input-root-outlined.mud-input-root-adorned-end.mud-input-root-margin-dense.mud-input-input-control.flex-grow-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f22a3168-dea8-4162-a9bf-3e4debc06697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>283a6b4c-d8c1-43e3-a7b6-5e0ad5b5591c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-input-slot mud-input-root mud-input-root-outlined mud-input-root-adorned-end mud-input-root-margin-dense mud-input-input-control flex-grow-0</value>
      <webElementGuid>7009a448-00f6-415d-a85a-48e4b193e3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0e1bb86-74f8-4a10-9118-c72dfb985062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;picker7756ec8b&quot;)/div[@class=&quot;mud-input-control mud-input-control-margin-dense&quot;]/div[@class=&quot;mud-input-control-input-container&quot;]/div[@class=&quot;mud-input mud-input-outlined mud-input-adorned-end mud-input-margin-dense mud-input-input-control flex-grow-0&quot;]/input[@class=&quot;mud-input-slot mud-input-root mud-input-root-outlined mud-input-root-adorned-end mud-input-root-margin-dense mud-input-input-control flex-grow-0&quot;]</value>
      <webElementGuid>26ec467d-3f04-47f0-8fb8-09b01f2fa7b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>a6a3f6d1-4017-4782-9392-05f2defda0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='picker7756ec8b']/div/div/div/input</value>
      <webElementGuid>5ffbc021-47c4-4128-8fa8-537d15af599c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published Date'])[1]/following::input[1]</value>
      <webElementGuid>2d2bae3a-249c-48da-9838-29efeb7792f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/following::input[2]</value>
      <webElementGuid>5a7c8cbc-2b57-4447-8342-3c4f6620d0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::input[2]</value>
      <webElementGuid>88ff3fb1-dc04-41e9-adba-d3f4faaa7e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[1]/preceding::input[3]</value>
      <webElementGuid>428826ce-dd74-47d5-8499-be967793777b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/div/div/div/div/input</value>
      <webElementGuid>475ca5d8-de7b-41fc-85d7-a7d3329e8a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a56b90c6-595e-4f67-bb67-ae55dfee5a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
